import type { Completeness, ListingDetail } from "@/lib/types";

const fullCompleteness: Completeness = {
  score: 3,
  level: "complete",
  checks: [
    { key: "day_night_photos", label: "Day & night photos", complete: true },
    { key: "digital_address", label: "Digital Address", complete: true },
    { key: "maintenance_policy", label: "Maintenance policy", complete: true },
  ],
};

const goodCompleteness: Completeness = {
  score: 2,
  level: "good",
  checks: [
    { key: "day_night_photos", label: "Day & night photos", complete: true },
    { key: "digital_address", label: "Digital Address", complete: false },
    { key: "maintenance_policy", label: "Maintenance policy", complete: true },
  ],
};

const shared = {
  negotiable: true,
  status: "published",
  created_at: "2026-08-20T10:00:00+00:00",
  updated_at: "2026-08-22T10:00:00+00:00",
  poster: { name: "Demo profile", role: "agent" as const },
  is_demo: true,
};

export const DEMO_LISTINGS: ListingDetail[] = [
  {
    ...shared,
    id: "demo-osu-courtyard",
    title: "Demo: airy two-bedroom apartment",
    type: "apartment",
    sale_mode: "rent",
    price_ghs: 4800,
    area: "Osu",
    beds: 2,
    baths: 2,
    size_m2: 92,
    deposit_months: 2,
    maintenance_policy: "landlord_annual",
    completeness: fullCompleteness,
    visual: "courtyard",
    digital_address: "GA-000-0000",
    color: "Warm sand exterior",
    description: "Illustrative listing used to preview the Accra Spaces experience. It is not a real property and cannot be booked.",
    amenities: ["parking", "air_conditioning", "water_tank", "security"],
    day_photos: ["demo/day/osu"],
    night_photos: ["demo/night/osu"],
    poster: { ...shared.poster, agent_commission: { type: "one_month_rent", value: 1, note: "Illustrative term" } },
  },
  {
    ...shared,
    id: "demo-spintex-shop",
    title: "Demo: street-facing retail space",
    type: "shop",
    sale_mode: "rent",
    price_ghs: 6500,
    area: "Spintex",
    beds: 0,
    baths: 1,
    size_m2: 120,
    deposit_months: 3,
    maintenance_policy: "tenant_deduct",
    completeness: fullCompleteness,
    visual: "storefront",
    digital_address: "GA-000-0000",
    color: "Charcoal frontage",
    description: "Illustrative retail listing showing how street visibility, day and night context, and agent terms will appear.",
    amenities: ["parking", "security", "backup_power"],
    day_photos: ["demo/day/spintex"],
    night_photos: ["demo/night/spintex"],
    poster: { ...shared.poster, agent_commission: { type: "percentage", value: 10, note: "Illustrative term" } },
  },
  {
    ...shared,
    id: "demo-adenta-house",
    title: "Demo: four-bedroom family house",
    type: "house",
    sale_mode: "sale",
    price_ghs: 875000,
    area: "Adenta",
    beds: 4,
    baths: 3,
    size_m2: 260,
    deposit_months: 0,
    maintenance_policy: "included",
    completeness: goodCompleteness,
    visual: "villa",
    description: "Illustrative sale listing. The interface separates sale pricing from monthly rent and keeps property terms visible.",
    amenities: ["parking", "fenced", "water_tank", "built_in_wardrobe"],
    day_photos: ["demo/day/adenta"],
    night_photos: ["demo/night/adenta"],
    poster: { name: "Demo profile", role: "landlord" },
  },
  {
    ...shared,
    id: "demo-east-legon-office",
    title: "Demo: flexible office with reception",
    type: "office",
    sale_mode: "rent",
    price_ghs: 12000,
    area: "East Legon",
    beds: 0,
    baths: 2,
    size_m2: 180,
    deposit_months: 2,
    maintenance_policy: "included",
    completeness: fullCompleteness,
    visual: "office",
    digital_address: "GA-000-0000",
    description: "Illustrative office listing showing the business-space filters included in the MVP.",
    amenities: ["parking", "air_conditioning", "generator", "security", "backup_power"],
    day_photos: ["demo/day/east-legon"],
    night_photos: ["demo/night/east-legon"],
    poster: { ...shared.poster, agent_commission: { type: "flat_fee", value: 3000, note: "Illustrative term" } },
  },
  {
    ...shared,
    id: "demo-cantonments-apartment",
    title: "Demo: calm three-bedroom apartment",
    type: "apartment",
    sale_mode: "rent",
    price_ghs: 7800,
    area: "Cantonments",
    beds: 3,
    baths: 3,
    size_m2: 148,
    deposit_months: 2,
    maintenance_policy: "landlord_annual",
    completeness: goodCompleteness,
    visual: "tower",
    description: "Illustrative apartment listing for interface review only. No real availability is represented.",
    amenities: ["parking", "air_conditioning", "elevator", "security", "water_heater"],
    day_photos: ["demo/day/cantonments"],
    night_photos: ["demo/night/cantonments"],
  },
  {
    ...shared,
    id: "demo-tema-townhouse",
    title: "Demo: gated three-bedroom townhouse",
    type: "house",
    sale_mode: "rent",
    price_ghs: 5200,
    area: "Tema",
    beds: 3,
    baths: 2,
    size_m2: 176,
    deposit_months: 2,
    maintenance_policy: "tenant_deduct",
    completeness: fullCompleteness,
    visual: "townhouse",
    digital_address: "GT-000-0000",
    description: "Illustrative townhouse listing used to demonstrate comparison details and safety guidance.",
    amenities: ["parking", "fenced", "water_tank", "security"],
    day_photos: ["demo/day/tema"],
    night_photos: ["demo/night/tema"],
    poster: { name: "Demo profile", role: "landlord" },
  },
];
